# Generated by Django 4.1.6 on 2023-02-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Menu name')),
                ('name1', models.CharField(max_length=50, verbose_name='Menu name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Menu name2')),
                ('name3', models.CharField(max_length=50, verbose_name='Menu name3')),
                ('name4', models.CharField(max_length=50, verbose_name='Menu name4')),
                ('img', models.ImageField(upload_to='media', verbose_name='Menu image')),
                ('img1', models.ImageField(upload_to='media', verbose_name='Menu image1')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menues',
            },
        ),
    ]
