# Generated by Django 4.1.6 on 2023-02-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Menu image'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='img1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Menu image1'),
        ),
    ]
