# Generated by Django 4.1.6 on 2023-02-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_menu_img_alter_menu_img1'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HomeHead name')),
                ('name1', models.CharField(max_length=50, verbose_name='HomeHead name1')),
                ('name2', models.CharField(max_length=50, verbose_name='HomeHead name2')),
            ],
            options={
                'verbose_name': 'HomeHead',
                'verbose_name_plural': 'HomeHeads',
            },
        ),
    ]
