# Generated by Django 4.1.6 on 2023-02-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Popular name')),
            ],
            options={
                'verbose_name': 'Popular',
                'verbose_name_plural': 'Popular',
            },
        ),
    ]
