# Generated by Django 4.1.6 on 2023-02-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='name1',
            field=models.CharField(max_length=50, null=True, verbose_name='Popular name1'),
        ),
    ]
