# Generated by Django 4.1.6 on 2023-02-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_popularimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='PopularEnd about')),
            ],
            options={
                'verbose_name': 'PopularEnd',
                'verbose_name_plural': 'Popularends',
            },
        ),
    ]
