# Generated by Django 4.1.6 on 2023-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_library_alter_popularend_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='LibraryInfo name')),
                ('name1', models.CharField(max_length=50, verbose_name='LibraryInfo name1')),
                ('name2', models.CharField(max_length=50, verbose_name='LibraryInfo name2')),
                ('name3', models.CharField(max_length=50, verbose_name='LibraryInfo name3')),
                ('name4', models.CharField(max_length=50, verbose_name='LibraryInfo name4')),
                ('about', models.TextField(verbose_name='LibraryInfo about')),
                ('about1', models.TextField(verbose_name='LibraryInfo about1')),
                ('about2', models.TextField(verbose_name='LibraryInfo about2')),
                ('about3', models.TextField(verbose_name='LibraryInfo about3')),
                ('img', models.ImageField(upload_to='media', verbose_name='LibraryInfo imge')),
            ],
            options={
                'verbose_name': 'LibraryInfo',
                'verbose_name_plural': 'LibraryInfos',
            },
        ),
    ]
