# Generated by Django 4.1.6 on 2023-02-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_libraryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='LibraryFoot name')),
            ],
            options={
                'verbose_name': 'LibraryFoot',
                'verbose_name_plural': 'LibraryFoots',
            },
        ),
    ]
