# Generated by Django 4.1.6 on 2023-02-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_libraryfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='BrowseMenu name')),
                ('name1', models.CharField(max_length=50, verbose_name='BrowseMenu name1')),
                ('name2', models.CharField(max_length=50, verbose_name='BrowseMenu name2')),
                ('name3', models.CharField(max_length=50, verbose_name='BrowseMenu name3')),
                ('name4', models.CharField(max_length=50, verbose_name='BrowseMenu name4')),
                ('img', models.ImageField(upload_to='media', verbose_name='BrowseMenu image')),
                ('img1', models.ImageField(upload_to='media', verbose_name='BrowseMenu image1')),
            ],
            options={
                'verbose_name': 'BrowseMenu',
                'verbose_name_plural': 'BrowseMenues',
            },
        ),
    ]
