# Generated by Django 4.1.6 on 2023-02-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_caruselhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruselhead',
            name='name1',
            field=models.CharField(max_length=50, null=True, verbose_name='CaruselHead name1'),
        ),
    ]
