# Generated by Django 4.1.6 on 2023-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_caruselhead_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Carusel name')),
                ('name1', models.CharField(max_length=50, verbose_name='Carusel name1')),
                ('about', models.TextField(verbose_name='Carusel about')),
                ('about1', models.TextField(verbose_name='Carusel about1')),
                ('about2', models.TextField(verbose_name='Carusel about2')),
                ('img', models.ImageField(upload_to='media', verbose_name='Carusel image')),
            ],
            options={
                'verbose_name': 'Carusel',
                'verbose_name_plural': 'Carusels',
            },
        ),
    ]
