# Generated by Django 4.1.6 on 2023-02-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tophead'),
    ]

    operations = [
        migrations.AddField(
            model_name='tophead',
            name='name1',
            field=models.CharField(max_length=50, null=True, verbose_name='TopHead name1'),
        ),
    ]
