# Generated by Django 4.1.6 on 2023-02-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_tophead_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Top name')),
                ('name1', models.CharField(max_length=50, verbose_name='Top name1')),
                ('about', models.TextField(verbose_name='Top about')),
                ('about1', models.TextField(verbose_name='Top about1')),
                ('img', models.ImageField(upload_to='media', verbose_name='Top image')),
            ],
            options={
                'verbose_name': 'Top',
                'verbose_name_plural': 'Tops',
            },
        ),
    ]
