# Generated by Django 4.1.6 on 2023-02-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TopFoot name')),
            ],
            options={
                'verbose_name': 'TopFoot',
                'verbose_name_plural': 'TopFoots',
            },
        ),
    ]
