# Generated by Django 4.1.6 on 2023-02-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_livestreambody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestreambody',
            name='about1',
        ),
    ]
