# Generated by Django 4.1.6 on 2023-02-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_livestreambody_about1'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='LiveStreamFoot name')),
            ],
            options={
                'verbose_name': 'LiveStreamFoot',
                'verbose_name_plural': 'LiveStreamFoots',
            },
        ),
    ]
