# Generated by Django 4.1.6 on 2023-02-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_browsefootfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='DetailMenu name')),
                ('name1', models.CharField(max_length=50, verbose_name='DetailMenu name1')),
                ('name2', models.CharField(max_length=50, verbose_name='DetailMenu name2')),
                ('name3', models.CharField(max_length=50, verbose_name='DetailMenu name3')),
                ('name4', models.CharField(max_length=50, verbose_name='DetailMenu name4')),
                ('img', models.ImageField(upload_to='media', verbose_name='DetailMenu image')),
                ('img1', models.ImageField(upload_to='media', verbose_name='DetailMenu image1')),
            ],
            options={
                'verbose_name': 'DetailMenu',
                'verbose_name_plural': 'DetailMenues',
            },
        ),
    ]
