# Generated by Django 4.1.6 on 2023-02-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_detailmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='DetailHead image')),
                ('img1', models.ImageField(upload_to='media', verbose_name='DetailHead image1')),
            ],
            options={
                'verbose_name': 'DetailHead',
                'verbose_name_plural': 'DetailHeads',
            },
        ),
    ]
