# Generated by Django 4.1.6 on 2023-02-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sandbox name')),
                ('name1', models.CharField(max_length=50, verbose_name='Sandbox name1')),
            ],
            options={
                'verbose_name': 'Sandbox',
                'verbose_name_plural': 'Sandboxes',
            },
        ),
    ]
