# Generated by Django 4.1.6 on 2023-02-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='about',
            field=models.TextField(null=True, verbose_name='sandbox about'),
        ),
        migrations.AddField(
            model_name='sandbox',
            name='about1',
            field=models.TextField(null=True, verbose_name='sandbox about1'),
        ),
    ]
