# Generated by Django 4.1.6 on 2023-02-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_sandbox_about_sandbox_about1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Action about')),
                ('about1', models.TextField(verbose_name='Action about1')),
                ('about2', models.TextField(verbose_name='Action about2')),
                ('about3', models.TextField(verbose_name='Action about3')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
