# Generated by Django 4.1.6 on 2023-02-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='DetailFoto image')),
            ],
        ),
    ]
