# Generated by Django 4.1.6 on 2023-02-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_detailfoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='DetailAbout about')),
            ],
            options={
                'verbose_name': 'DetailAbout',
                'verbose_name_plural': 'DetailAbout',
            },
        ),
    ]
