# Generated by Django 4.1.6 on 2023-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_detailabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='DetailFoot name')),
            ],
            options={
                'verbose_name': 'DetailFoot',
                'verbose_name_plural': 'DetailFoots',
            },
        ),
    ]
