# Generated by Django 4.1.6 on 2023-02-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_detailfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='RelatedHead name')),
                ('name1', models.CharField(max_length=50, verbose_name='RelatedHead name1')),
            ],
            options={
                'verbose_name': 'RelatedHead',
                'verbose_name_plural': 'RelatedHeads',
            },
        ),
    ]
