# Generated by Django 4.1.6 on 2023-02-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_relatedhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='RelatedInfo name')),
                ('name1', models.CharField(max_length=50, verbose_name='RelatedInfo name1')),
                ('img', models.ImageField(upload_to='max', verbose_name='RelatedInfo image')),
            ],
            options={
                'verbose_name': 'RelatedInfo',
                'verbose_name_plural': 'RelatedInfos',
            },
        ),
    ]
