# Generated by Django 4.1.6 on 2023-02-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_relatedinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedinfo',
            name='about',
            field=models.TextField(null=True, verbose_name='RelatedInfo about'),
        ),
        migrations.AddField(
            model_name='relatedinfo',
            name='about1',
            field=models.TextField(null=True, verbose_name='RelatedInfo about1'),
        ),
    ]
