# Generated by Django 4.1.6 on 2023-02-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_relatedinfo_about_relatedinfo_about1'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamsMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='StreamsMenu name')),
                ('name1', models.CharField(max_length=50, verbose_name='StreamsMenu name1')),
                ('name2', models.CharField(max_length=50, verbose_name='StreamsMenu name2')),
                ('name3', models.CharField(max_length=50, verbose_name='StreamsMenu name3')),
                ('name4', models.CharField(max_length=50, verbose_name='StreamsMenu name4')),
                ('img', models.ImageField(upload_to='media', verbose_name='StreamsMenu image')),
                ('img1', models.ImageField(upload_to='media', verbose_name='StreamsMenu image')),
            ],
            options={
                'verbose_name': 'StreamsMenu',
                'verbose_name_plural': 'StreamsMenues',
            },
        ),
    ]
