# Generated by Django 4.1.6 on 2023-02-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_streamshead'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamsCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='StreamsCarusel name')),
                ('name1', models.CharField(max_length=50, verbose_name='StreamsCarusel name1')),
                ('name2', models.CharField(max_length=50, verbose_name='StreamsCarusel name2')),
                ('about', models.TextField(verbose_name='StreamsCarusel about')),
                ('about1', models.TextField(verbose_name='StreamsCarusel about1')),
                ('img', models.ImageField(upload_to='media', verbose_name='StreamsCarusel image')),
            ],
            options={
                'verbose_name': 'StreamsCarusel',
                'verbose_name_plural': 'StreamsCarusels',
            },
        ),
    ]
