# Generated by Django 4.1.6 on 2023-02-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_popularhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='PopularFoto name')),
                ('name1', models.CharField(max_length=50, verbose_name='PopularFoto name1')),
                ('name2', models.CharField(max_length=50, verbose_name='PopularFoto name2')),
                ('about', models.TextField(verbose_name='PopularFoto about')),
                ('about1', models.TextField(verbose_name='PopularFoto about1')),
                ('img', models.ImageField(upload_to='media', verbose_name='PopularFoto image')),
                ('img1', models.ImageField(upload_to='media', verbose_name='PopularFoto image1')),
            ],
            options={
                'verbose_name': 'PopularFoto',
                'verbose_name_plural': 'PopularFotos',
            },
        ),
    ]
