# Generated by Django 4.1.6 on 2023-02-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_popularfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProfilMenu name')),
                ('name1', models.CharField(max_length=50, verbose_name='ProfilMenu name1')),
                ('name2', models.CharField(max_length=50, verbose_name='ProfilMenu name2')),
                ('name3', models.CharField(max_length=50, verbose_name='ProfilMenu name3')),
                ('name4', models.CharField(max_length=50, verbose_name='ProfilMenu name4')),
                ('img', models.ImageField(upload_to='media', verbose_name='ProfilMenu image')),
                ('img1', models.ImageField(upload_to='media', verbose_name='ProfilMenu image')),
            ],
            options={
                'verbose_name': 'ProfilMenu',
                'verbose_name_plural': 'ProfilMenues',
            },
        ),
    ]
