# Generated by Django 4.1.6 on 2023-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_profilmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProfilHead name')),
                ('name1', models.CharField(max_length=50, verbose_name='ProfilHead name1')),
                ('name2', models.CharField(max_length=50, verbose_name='ProfilHead name2')),
                ('about', models.TextField(verbose_name='ProfilHead about')),
                ('about1', models.TextField(verbose_name='ProfilHead about1')),
                ('about2', models.TextField(verbose_name='ProfilHead about2')),
                ('about3', models.TextField(verbose_name='ProfilHead about3')),
                ('about4', models.TextField(verbose_name='ProfilHead about4')),
                ('about5', models.TextField(verbose_name='ProfilHead about5')),
                ('about6', models.TextField(verbose_name='ProfilHead about6')),
                ('about7', models.TextField(verbose_name='ProfilHead about7')),
                ('about8', models.TextField(verbose_name='ProfilHead about8')),
                ('img', models.ImageField(upload_to='media', verbose_name='ProfilHead image')),
            ],
            options={
                'verbose_name': 'ProfilHead',
                'verbose_name_plural': 'ProfilHeads',
            },
        ),
    ]
