# Generated by Django 4.1.6 on 2023-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_profilhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProfilClip name')),
                ('name1', models.CharField(max_length=50, verbose_name='ProfilClip name1')),
            ],
            options={
                'verbose_name': 'ProfilClip',
                'verbose_name_plural': 'ProfilClips',
            },
        ),
    ]
