# Generated by Django 4.1.6 on 2023-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_profilclip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Clip name')),
                ('about', models.TextField(verbose_name='Clip about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Clip image')),
            ],
            options={
                'verbose_name': 'Clip',
                'verbose_name_plural': 'Clips',
            },
        ),
    ]
