# Generated by Django 4.1.6 on 2023-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_clipfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProfilLibrary name')),
                ('name1', models.CharField(max_length=50, verbose_name='ProfilLibrary name1')),
            ],
            options={
                'verbose_name': 'ProfilLibrary',
                'verbose_name_plural': 'ProfilLibraries',
            },
        ),
    ]
