# Generated by Django 4.1.6 on 2023-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_profillibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilLibraryFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ProfilLibraryFoto name')),
                ('name1', models.CharField(max_length=50, verbose_name='ProfilLibraryFoto name1')),
                ('name2', models.CharField(max_length=50, verbose_name='ProfilLibraryFoto name2')),
                ('name3', models.CharField(max_length=50, verbose_name='ProfilLibraryFoto name3')),
                ('name4', models.CharField(max_length=50, verbose_name='ProfilLibraryFoto name4')),
                ('about', models.TextField(verbose_name='ProfilLibraryFoto about')),
                ('about1', models.TextField(verbose_name='ProfilLibraryFoto about1')),
                ('about2', models.TextField(verbose_name='ProfilLibraryFoto about2')),
                ('about3', models.TextField(verbose_name='ProfilLibraryFoto about3')),
                ('img', models.ImageField(upload_to='media', verbose_name='ProfilLibraryFoto image')),
            ],
            options={
                'verbose_name': 'ProfilLibraryFoto',
                'verbose_name_plural': 'ProfilLibraryFotos',
            },
        ),
    ]
