from django.contrib import admin
from .models import Menu, HomeHead, Popular, PopularImage, PopularEnd, Library, LibraryInfo, LibraryFoot, BrowseMenu, CaruselHead, Carusel, TopHead, Top, TopFoot, LiveStreamHead, LiveStreamBody, LiveStreamFoot, BrowseFootHead, BrowseFootFoto, BrowseFootFoot, DetailMenu, DetailHead, Detail, Sandbox, Action, DetailFoto, DetailAbout, DetailFoot, RelatedHead, RelatedInfo, StreamsMenu, StreamsHead, StreamsCarusel, StreamsTop, TopInfo, PopularHead, PopularFoto, PopularFoot, ProfilMenu, ProfilHead, ProfilClip, Clip, ClipFoot, ProfilLibrary, ProfilLibraryFoto

# Register your models here.

admin.site.register(Menu)
admin.site.register(HomeHead)
admin.site.register(Popular)
admin.site.register(PopularImage)
admin.site.register(PopularEnd)
admin.site.register(Library)
admin.site.register(LibraryInfo)
admin.site.register(LibraryFoot)
admin.site.register(BrowseMenu)
admin.site.register(CaruselHead)
admin.site.register(Carusel)
admin.site.register(TopHead)
admin.site.register(Top)
admin.site.register(TopFoot)
admin.site.register(LiveStreamHead)
admin.site.register(LiveStreamBody)
admin.site.register(LiveStreamFoot)
admin.site.register(BrowseFootHead)
admin.site.register(BrowseFootFoto)
admin.site.register(BrowseFootFoot)
admin.site.register(DetailMenu)
admin.site.register(DetailHead)
admin.site.register(Detail)
admin.site.register(Sandbox)
admin.site.register(Action)
admin.site.register(DetailFoto)
admin.site.register(DetailAbout)
admin.site.register(DetailFoot)
admin.site.register(RelatedHead)
admin.site.register(RelatedInfo)
admin.site.register(StreamsMenu)
admin.site.register(StreamsHead)
admin.site.register(StreamsCarusel)
admin.site.register(StreamsTop)
admin.site.register(TopInfo)
admin.site.register(PopularHead)
admin.site.register(PopularFoto)
admin.site.register(PopularFoot)
admin.site.register(ProfilMenu)
admin.site.register(ProfilHead)
admin.site.register(ProfilClip)
admin.site.register(Clip)
admin.site.register(ClipFoot)
admin.site.register(ProfilLibrary)
admin.site.register(ProfilLibraryFoto)

